### PR TITLE
Beautify regular expression

### PR DESCRIPTION
**Pull request by azat-io**

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@azat-io Can you close and reopen the PR to trigger the CLA Bot again please and against current master please? Or send a new one as you prefer 😛

**Comment by azat-io** [comment]
@michael-ciniawsky Done!

**Comment by michael-ciniawsky** [comment]
@azat-io The CLA needs to be signed 😛  Close and reopen the PR to trigger the Bot

**Comment by azat-io** [comment]
@michael-ciniawsky Done

**Comment by michael-ciniawsky** [comment]
@azat-io Thx

**Pull request merged**
