### PR TITLE
Fix URI for PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by ykzts**
`https://cla.js.foundation/webpack/webpack.js.org` -> `https://cla.js.foundation/webpack-contrib/compression-webpack-plugin`

other repo?

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
thx, but both yield the same result and the CLA needs to be signed only once by a contributor to `webpack-contrib`, we keep this file in sync across repos :)

**Comment by ykzts** [comment]
I see. But, Is `webpack` and `webpack-contrib` the same?

**Comment by michael-ciniawsky** [comment]
All `loaders` && `plugins` which resided under `webpack` + ecosystem important ones, where moved to `webpack-contrib`, `webpack` && `webpack-contrib` belong together. `webpack.js.org` is mainly for documentation, but it is the homepage for both `webpack` && `webpack-contrib` aswell :)

**Comment by ykzts** [comment]
Okay! I understood.

**Pull request closed without merging**
