### PR TITLE
feat: remove new redundant options arg from algorithm

### PR DESCRIPTION
**Pull request by h4l**
It was introduced in 0.3.1 and broke configurations passing an explicit
algorithm function, as the signature used to be `function(buff, cb)`.

This implements option 1 from #25.

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@h4l In any case please close and reopen the PR to trigger the CLA Bot again 😛

**Comment by bebraw** [comment]
I would go with this over https://github.com/webpack-contrib/compression-webpack-plugin/pull/27 . You have to communicate the change well so people how to migrate and it has to be released as a major version.

**Comment by michael-ciniawsky** [comment]
@h4l friendly ping :)

**Comment by h4l** [comment]
@michael-ciniawsky sorry for the delay, I've signed the CLA now. Would you like me to rebase up to the current master?

**Comment by michael-ciniawsky** [comment]
@h4l yep, please rebase :stuck_out_tongue:

**Comment by h4l** [comment]
@michael-ciniawsky I've rebased. Seems like we could do with some tests though.

**Comment by michael-ciniawsky** [comment]
@h4l There are no tests for `compression-webpack-plugin` atm 😛 , if you want to propose/setup some, highly welcome and appreciated, we are also always looking for maintainers borrowing us a hand or two 😉

**Comment by d3viant0ne** [comment]
I'm starting to feel like a broken record with this but if we are going to cut a major, we will need to do it along with defaults.

**Comment by evilebottnawi** [comment]
Close due inactive. Feel free recreate new PR. Thanks!

**Pull request closed without merging**
