### PR TITLE
Use `##` for releases in CHANGELOG.md

### PR DESCRIPTION
**Pull request by aried3r**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update**
- [x] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

I believe this follows the formatting of the other releases.

### CODE REVIEW

**Review by evilebottnawi — CHANGES_REQUESTED** [review]
No need to change changelog, it is auto generated

**Comment by aried3r** [comment]
> No need to change changelog, it is auto generated

Why is it generating "4.0.1" as a subsection of "5.0.0"? Are smaller headers used to indicate patch releases? That doesn't seem to be true for older releases in the change log.

**Comment by evilebottnawi** [comment]
@aried3r you can discuss about it in `standard-release` repo https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/package.json#L73

**Comment by aried3r** [comment]
Thank you, I'll have a look!

**Pull request closed without merging**
