### PR TITLE
chore(deps): update schema-utils to the latest version

### PR DESCRIPTION
**Pull request by jamesgeorge007**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case
Updated `schema-utils` to `v2.6.4`.

### Breaking Changes
Nothing

### Additional Info
Nothing

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
@evilebottnawi what is leads to the CI failure :thinking:

**Comment by jamesgeorge007** [comment]
@evilebottnawi what leads to the CI failure :thinking:

**Comment by evilebottnawi** [comment]
Need update test snapshots

**Comment by evilebottnawi** [comment]
Hm, broken on next, need ivnestigate

**Comment by evilebottnawi** [comment]
Done in master, anyway thanks for the PR

**Pull request closed without merging**
