### PR TITLE
Add “Using Brotli”

### LINKED ISSUE #118: Brotli support
* Operating System: macOS Mojave (10.14.3)
* Node Version: 10.15.2
* NPM Version: 6.4.1
* webpack Version: 4.28.4
* webpack-defaults Version: N/A

### Feature Proposal
Node 11.7.0 has [native support](https://nodejs.org/api/zlib.html#zlib_zlib_createbrotlicompress_options) for Brotli compression in its `zlib` module.

### Feature Use Case
- Smaller files compared to Gzip:
    - image **credit:** https://blog.kowalczyk.info/article/c11d3c20753445618b98d18be5ce037e/zopfli-vs.-brotli-vs.-gzip.html

- Not having to rely on external libraries like [iltorb](https://github.com/MayhemYDG/iltorb) used in [brotli-webpack-plugin](https://github.com/mynameiswhm/brotli-webpack-plugin)

### PR DESCRIPTION
**Pull request by khalwat**
Signed-off-by: Andrew Welch <andrew@nystudio107.com>

fixes #118

### CODE REVIEW

**Comment by evilebottnawi** [comment]
fixes #118

**Comment by evilebottnawi** [comment]
@khalwat Can you accept CLA?

**Comment by khalwat** [comment]
I did accept the CLA

**Comment by khalwat** [comment]
@evilebottnawi I did accept the CLA.

**Pull request merged**
