### PR TITLE
refactor: use `emit` event instead of `this-compilation`

### LINKED ISSUE #30: doesn't seem to compress HTML from html-webpack-plugin

### LINKED ISSUE #57: Using Compression plugin alongside 'html-webpack-plugin'
Is it possible to make the Html Webpack plugin insert a link to the .gz build file instead of the normal .js build file?

Is this even the right place to ask this question??

Thanks for your help, and thanks for your work on a great plugin!

### LINKED ISSUE #62: Doesn't hook up my files
Hello! I'm trying to make build and deployment system for my project.  I want to be able to serve gzipped vendor and custom JS files, and merged and gzipped single CSS file (cause vendor chunk also has some css in it). If I don't merge css with merge-files-webpack-plugin, everything goes well and I see 2 css files in the output, BUT when merging, I see my combined style.css intact(with deleteOriginalAssets: true) and no gzipped css. Seems like  something's wrong with the order, or RegExp, or something...Please help! Webpack 2. Here's the code:

```
var path = require('path');
var webpack = require ('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var MergeFilesPlugin = require('merge-files-webpack-plugin');
var OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
var cssProcessor = require('cssnano');
var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
var CompressionPlugin = require('compression-webpack-plugin');


const VENDOR_LIBS = [ 'axios', 'crypto-js', 'jstimezonedetect', 'lodash', 'normalizr', 'react-motion', 'react', 'react-dom', 'react-router', 'redux-form', 'react-redux', 'react-router-redux', 'react-swipeable-views', 'react-tap-event-plugin', 'recompose', 'redux', 'redux-form-material-ui', 'redux-mediaquery', 'redux-thunk', 'reselect', 'reset-css', 'socket.io-client', 'material-ui/FlatButton', 'material-ui/TextField', 'material-ui/Table', 'material-ui/SelectField', 'material-ui/MenuItem', 'material-ui/Stepper', 'material-ui/Checkbox', 'material-ui/styles/colors',
'material-ui/Tabs', 'material-ui/FloatingActionButton', 'material-ui/DropDownMenu', 'material-ui/utils/colorManipulator', 'material-ui/Dialog', 'material-ui/CircularProgress', 'material-ui/Snackbar', 'material-ui/styles/MuiThemeProvider', 'material-ui/styles/getMuiTheme', 'material-ui/styles/spacing' ];

const config = {
  entry: {
  app: [ 'babel-polyfill', './app/index.js' ],
  vendor: VENDOR_LIBS
  },

  output: {
    path: path.resolve(__dirname, 'build'),
    publicPath: 'build/',
    filename: '[name].js',
  },

  plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(),

    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify('production')
      }
    }),

    new ExtractTextPlugin('[name].css'),

    new MergeFilesPlugin({
           filename: 'style.css',
           test: /\.css$/,
           deleteSourceFiles: true
       }),

       new OptimizeCssAssetsPlugin({
         assetNameRegExp: /\.css$/g,
         cssProcessor: cssProcessor,
         cssProcessorOptions: { discardComments: {removeAll: true} },
         safe: true,
         canPrint: true
       }),

       new CompressionPlugin({
         asset: 'gzip/[file][query]',
         algorithm: 'gzip',
         test: /style.css/g,
         threshold: 0,
         minRatio: 0.8,
         deleteOriginalAssets: true
       }),


    new webpack.optimize.CommonsChunkPlugin({
        name: 'vendor',
        minChunks: Infinity,
        filename: '[name].js',
      }),



    new webpack.optimize.UglifyJsPlugin({
      sourceMap: false,
      compressor: {
        warnings: false
      }
    }),

  /*  new BundleAnalyzerPlugin({
            analyzerMode: 'static'
        }), */



    new CompressionPlugin({
      asset: 'gzip/[file][query]',
      algorithm: 'gzip',
      test: /\.js$/g,
      threshold: 0,
      minRatio: 0.8
    //  ,deleteOriginalAssets: true
  })



  ],
  module: {
    rules: [

      {
        test: /\.json$/,
        use: 'json-loader'
      },
      {
        test: /\.(png|jpe?g|gif|svg)$/,
        use: [
          {
            loader: 'file-loader?name=[path][name].[ext]',
            options: { limit: 40000, outputPath: 'images/' }
          },
          'image-webpack-loader'
            ]
      },
      {
        test: /\.css$/,
         use: ExtractTextPlugin.extract({
           fallback: 'style-loader',
           use: [
            'css-loader?modules&localIdentName=[path][name]_[local]--[hash:base64:8]',
             {
               loader: 'postcss-loader',
               options: {
                 importLoaders: 1
               }
             }

           ]
         })

      },
      {
        use: [{
          loader: 'babel-loader',
          options: { presets: ['react', 'es2015', 'stage-1'] },
        }],
        test: /\.js$/,
        exclude: /node_modules/
      }
    ]
  },
  resolve: {
    extensions: ['*', '.js', '.jsx', '.json']
  },
  devtool: false,
  devServer: {

    historyApiFallback: true,
    contentBase: './app'
  }
};

module.exports = config;
```

### LINKED ISSUE #63: Compressing files copied by 'copy-webpack-plugin'
Hello,

This is my setup:
```
let CompressionPlugin = require('compression-webpack-plugin');
let CopyWebpackPlugin = require('copy-webpack-plugin');
...
        new CopyWebpackPlugin([{ from: 'src/assets', to: 'assets' }]),

        new CompressionPlugin({
            asset: '[path].gz',
            algorithm: 'gzip',
            test:  /\.(js|css|map|po)$/,
            // threshold: 10240,
            minRatio: 10  // 0.8
        }),
```
The problem is that .po files, which are in src/assets/translations, and which are copied by the CopyWebpackPlugin don't get compressed by the CompressionPlugin.
Not sure who's plugin fault it is. :)
Is it possible to get it work as intended?

Thanks!

### PR DESCRIPTION
**Pull request by ijpiantanida**
### Notable Changes

Given that compression is most likely one of the last steps on the pipeline
chain, it makes sense that this plugin uses the `emit` event which is the last
step to add/modify assets before they're written to disk.

This plays nicely with other plugins that create and delete files
on the fly AFTER they're compiled
(for example https://github.com/jtefera/merge-files-webpack, which is the
recommeded solution for this issue
webpack-contrib/extract-text-webpack-plugin#179)

### Issues

- Fixes #30 
- Fixes #57 
- Fixes #62 
- Fixes #63

> edited by @michael-ciniawsky (Formatting)

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
Marked as (:label: Minor) for now, but not 💯 if this should be considered a breaking change, personally I don't think so

**Comment by genu** [comment]
Whats holding up this from being pulled?

**Comment by NitroBAY** [comment]
```
  entry: path.resolve(__dirname, 'client/src'),
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'client/dist'),
  },
  module: {
    rules: [
      {
        test: /\.html?$/,
        use: ['html-loader'],
      },
    ],
  },
  plugins: [
    new HtmlPlugin({
      filename: 'index.html',
    }),
    new CompressionPlugin(),
  ],
  target: 'web',
```
With this config my js gets compressed but not my HTML why ??

**Comment by evilebottnawi** [comment]
@NitroBAY compression just create `*.gz` files and don't minify html content

**Comment by NitroBAY** [comment]
Yes I know but it creates a js file with its gz counterpart but the html file created by HtmlWebpackPlugin (shorten by HtmlPlugin here) is not having its gz version of it. I missing something because I'm new to webpack maybe but then what is it ?

**Comment by NitroBAY** [comment]
Even without htmlplugin but with file-loader/extract-loader/html-loader : 
```
const client = {
  entry: path.resolve(__dirname, 'client/src/index.js'),
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'client/dist'),
    publicPath: '.',
  },
  module: {
    rules: [{
      test: /\.html$/,
      use: [
        {
          loader: 'file-loader',
          options: {
            name: '[name].[ext]',
          },
        },
        {
          loader: 'extract-loader',
        },
        {
          loader: 'html-loader',
          options: {
            minimize: minifyOption,
          },
        },
      ],
    }],
  },
  plugins: [
    new CompressionPlugin(),
  ],
  target: 'web',
};
```
The output html is not gzipped is it normal ? How do I gzip html ?

**Comment by NitroBAY** [comment]
@evilebottnawi

**Comment by evilebottnawi** [comment]
@NitroBAY seems you have default `threshold` https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/src/index.js#L87 (i.e. `gzip` is not recommend for this html), just change value

**Comment by NitroBAY** [comment]
@evilebottnawi the default is 0 bytes. My html is not 130 bytes so it's greater than 0. Even when I set to 1 or whatever value it doesn't change a thing. 
```
                                Asset       Size  Chunks             Chunk Names
95e8d881b9d1f966529393f226969b18.html  130 bytes          [emitted]
                              main.js  690 bytes       0  [emitted]  main
                           main.js.gz  399 bytes          [emitted]
Entrypoint main = main.js
   [0] ./node_modules/html-loader!./client/src/index.html 105 bytes {0} [built]
   [1] ./client/src/index.js 88 bytes {0} [built]
```

**Comment by nerdmax** [comment]
Any solutions to that? I just want the `html-webpack-plugin` to reference the .gz file

**Comment by nerdmax** [comment]
I've resolved this issue by implementing this plugin: [html-webpack-brotli-plugin](https://github.com/nerdmax/html-webpack-brotli-plugin).

Eg:
```javascript
plugins: [
  new HtmlWebpackPlugin({
    addBrotliExtension: true
  }),
  new BrotliPlugin({
    asset: "[path].br[query]",
    test: /\.(js|css|html|svg)$/,
    threshold: 10240,
    minRatio: 0.8
  }), // brotli plugin will generate the xxx.js.br file
  new HtmlWebpackBrotliPlugin()
];
```

Please create an issue [here](https://github.com/nerdmax/html-webpack-brotli-plugin/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) if you encounter any issues related to that plguin.

**Comment by nerdmax** [comment]
I've resolved this issue by implementing this plugin: [html-webpack-change-assets-extension-plugin](https://github.com/nerdmax/html-webpack-change-assets-extension-plugin).

Eg:
```javascript
plugins: [
  new HtmlWebpackPlugin({
    jsExtension: ".gz"
  }),
  new CompressionPlugin(), // compression plugin will generate the xxx.js.gz file
  new HtmlWebpackChangeAssetsExtensionPlugin()
];
```

Please create an issue [here](https://github.com/nerdmax/html-webpack-change-assets-extension-plugin/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) if you encounter any issues related to that plguin.

**Comment by hedefalk** [comment]
@nerdmax Thx! Using it and it works!

I read quite a few issues that was being closed, for instance https://github.com/jantimon/html-webpack-plugin/issues/61

I just want to clarify my need. Using only 

```
new HtmlWebpackPlugin({
      template: './src/index.html',
      jsExtension: '.gz',
    }),
    new CompressionPlugin({
      test: /\.js(\?.*)?$/i,
    }),
```

I get:

```
~/d/p/kb-frontend ❯❯❯ ll dist/marko.*                                                                                                                                                                master ✭ ✱
-rw-r--r--  1 viktor  staff   382K Oct  7 22:39 dist/marko.7299746349ba7d1314da.js
-rw-r--r--  1 viktor  staff   108K Oct  7 22:39 dist/marko.7299746349ba7d1314da.js.gz
-rw-r--r--  1 viktor  staff   1.8M Oct  7 22:39 dist/marko.7299746349ba7d1314da.js.map
```

But then the output html isn't using the gz:

```
/d/p/kb-frontend ❯❯❯ cat dist/index.html                                                                                                                                                            master ✭ ✱
<!doctype html>
<html>
       …
    <script type="text/javascript" src="marko.7299746349ba7d1314da.js"></script>
    …
</html>
```

no matter which order I use HtmlWebpackPlugin and CompressionPlugin.

But with:

```
    new HtmlWebpackPlugin({
      template: './src/index.html',
      jsExtension: '.gz',
    }),
    new CompressionPlugin({
      test: /\.js(\?.*)?$/i,
    }),
    new HtmlWebpackChangeAssetsExtensionPlugin(),
```

I have:

```
~/d/p/kb-frontend ❯❯❯ cat dist/index.html                                                                                                                                                            master ✭ ✱
<!doctype html>
<html>
       …
    <script type="text/javascript" src="marko.7299746349ba7d1314da.js.gz"></script>
    …
</html>
```

Anyway, HtmlWebpackChangeAssetsExtensionPlugin worked for my use case.

**Comment by pimvanderheijden** [comment]
Is it me or is this simply broken with webpack v5? 

Running
```
node --trace-deprecation node_modules/webpack/bin/webpack.js --config ./webpack-configs/webpack.prod-client.js
```

I get
```
[webpack-cli] TypeError: Cannot read property 'tapAsync' of undefined                                                                                                                                              
    at ... /node_modules/html-webpack-change-assets-extension-plugin/dist/html-webpack-change-assets-extension-plugin.umd.js:25:36
 ```
 
 Node 14
 Webpack v5
 html-webpack-change-assets-extension-plugin 1.2.0
 html-webpack-plugin 5.3.2
 
In html-webpack-plugin `jsExtension` seems to be deprecated, it doesn't appear to do anything and it's not in the docs.
Other than I've nothing worth mentioning in my html-webpack-plugin definition.
Also changing the order of creating the plugins does not change a thing.

**Comment by pimvanderheijden** [comment]
This is my webpack config by the way:

```
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const CompressionPlugin = require('compression-webpack-plugin')
const HtmlWebpackChangeAssetsExtensionPlugin = require('html-webpack-change-assets-extension-plugin')

module.exports = {
    mode   : 'production',
    target : 'web',
    output: {
        filename      : '[name]-bundle.[fullhash].js',
        chunkFilename : '[name].js',
        path          : path.resolve(__dirname, '../build/'),
        publicPath    : '/'
    },
    plugins: [
        new HtmlWebpackPlugin({
            template           : 'index.pug',
            jsExtension        : '.gz',
        }),
        new CompressionPlugin({
            test: /\.(js|css|html|svg|png|gif|jpg|woff|woff2|eot|ttf|otf)$/
        }),
        new HtmlWebpackChangeAssetsExtensionPlugin()
    ]
}
```

**Pull request merged**
