### PR TITLE
fix setting compression level for brotliCompress

### LINKED ISSUE #154: Incorrect Brotli example
Documentation Is:

- [ ] Missing
- [x] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
The Brotli examples in the README do not correctly set the `compressionOptions`. The `BROTLI_PARAM_QUALITY` parameter is the equivalent to zlib's `level` option in terms of functionality, but not naming.

### Your Proposal for Changes
1. Revise the examples to set the Brotli parameters correctly.

```js
const zlib = require('zlib');
...
compressionOptions: {
  params: {
    [zlib.constants.BROTLI_PARAM_QUALITY]: 11
  }
}
```

2. Update the note to be more clear about `BROTLI_PARAM_QUALITY` being functionally equivalent to `level`, but not syntactically. 

3. Update note regarding Node version as Brotli native support was backported to [Node 10.16](https://github.com/nodejs/node/pull/27681).

### PR DESCRIPTION
**Pull request by 180254**
This PR contains a:

- [X] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [X] **test update** 
- [ ] **typo fix**
- [X] **metadata update**

### Motivation / Use-Case

Fixes #154.

### Breaking Changes

No

### Additional Info

No

### CODE REVIEW

**Review by evilebottnawi — COMMENTED** [review]
Maybe we should fix it in code too?

**Comment by 180254** [comment]
What fixes would you like to see in the code? It comes to my mind that default parameters may be passed depending on the algorithm. Do you see any other changes needed?

**Comment by evilebottnawi** [comment]
I mean this https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/src/index.js#L70, we should always set to maximum, for brotly too

**Comment by 180254** [comment]
I think it's done now. Please check this PR again.

**Pull request merged**
